FROM python:3.7-buster

WORKDIR /app

RUN apt-get update && apt-get upgrade -y

# Add source code
COPY divdet/*.py ./divdet/
COPY requirements.txt .
COPY setup.py .

# Install everything via pip
RUN pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install -e .
